### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by ghost** [olegario96/pyusuggest#1]
When there are no results:
ubersuggest.look_up()
  File "/Users/admin/.local/lib/python3.7/site-packages/pyusuggest/ubersuggest.py", line 120, in look_up
    self.results = json_result.get('results').get('processed_keywords')
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by olegario96** [comment]
Have you created the `Ubersuggest` object following the documentation? You have to creat the object passing as parameter the keyword you want to find, or set manually. Ex:

```
keyword = 'algorithm'
ubersuggest = Ubersuggest(keyword)
ubersuggest.look_up()
....
```

**Comment by olegario96** [comment]
Closing this issue due to the inactivity. Feel free to open it again.

**Comment by ghost** [comment]
yes, i do it

for keyword in palabrasClave:
  print('Analizando {}'.format(keyword))
  print('{} de {}'.format(palabra, len(palabrasClave)))
  ubersuggest.set_keyword(keyword)
  # Primero idioma - segundo país. Por ejemplo en-us
  ubersuggest.set_locale('es-es')
  analitica = ubersuggest.look_up()

**Comment by olegario96** [comment]
```
from pyusuggest import Ubersuggest
if __name__ == '__main__':
    u = Ubersuggest('')
    keywords = ['java', 'python', 'algorithm']
    for keyword in keywords:
        print('Analyzing {}'.format(keyword))
        print('{} of {}'.format(keyword, len(keywords)))
        u.set_keyword(keyword)
        analytic = u.look_up()
```

Using this code in a script file, does work properly.

**Comment by olegario96** [comment]
This looks like to be a problem with the Ubersuggest. Debugging the code with `requests` sometimes you may receive this message:

```
{"message": "Endpoint request timed out"}
``` 

A new version of this library will be implemented prepared to throw an exception when this happens.

**Comment by Lekeitio** [comment]
Thanks

**Comment by ghost** [comment]
May be using a timeout may help:
requests.get('http://www.google.com', timeout=(5, 14))

**Comment by olegario96** [comment]
This issue is solved in version 1.0.5. Please update your library.

**Comment by ghost** [comment]
Hi Gustavo, I've updated your solution withe the "timeout" option on the
"get" (line 128) and now I don't experience the problem:

while (tries < 3 and not success):
            res = requests.get(url_formatted, timeout=(5, 60)).text
            if not json.loads(res).get('message') == 'Endpoint request
timed out':
                success = True
            tries += 1

Thanks a lot for your development, really useful for me.

Luis

**Comment by Yun-Lee** [comment]
Hi @olegario96,
I've bumped into the very same problem by getting the -->
AttributeError: 'NoneType' object has no attribute 'get'.
I'm sure I downloaded the latest pyusuggest library, i've followed the sample code on your document:

keyword = 'algorithm'
ubersuggest = Ubersuggest(keyword)
ubersuggest.set_locale('es-es')
#requests data from ubersuggest
ubersuggest.look_up()

Is there anything I can do to fix this?
Thanks a lot

**Comment by Yun-Lee** [comment]
Just want to say that I've also tried to add "timeout" option on the "get" (line 128) as @Lekeitio  mentioned, yet I still got the problem. 
Thanks so much in advance.

**Comment by jfbernier88** [comment]
It doesn't seem to work for me neither. added the timeout in the library didn't change anything.

`from pyusuggest import Ubersuggest
keyword = 'algorithm'
ubersuggest = Ubersuggest(keyword)
ubersuggest.look_up()`
